common/models/Unidade.php
<?php

namespace common\models;

/**
 * This is the model class for table "unidade".
 *
 * @property integer $id
 * @property string $numero
 * @property integer $condominioId
 * @property integer $proprietarioId
 *
 * @property Debito[] $debitos
 * @property Condominio $condominio
 * @property Proprietario $proprietario
 */
class Unidade extends MainModel
{
    /**
     * @inheritdoc
     *
     * @return query\UnidadeQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new query\UnidadeQuery(get_called_class());
    }

    /* @inheritdoc */
    public function modelName()
    {
        return $this->numero . ' - ' . $this->condominio->razaoSocial;
    }

    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'unidade';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['id', 'condominioId', 'proprietarioId'], 'integer'],
            [['condominioId'], 'required'],
            [['numero'], 'string', 'max' => 10],
            [['totalDebitos'], 'number'],
            [['condominioId'], 'exist', 'skipOnError' => true, 'targetClass' => Condominio::className(), 'targetAttribute' => ['condominioId' => 'id']],
            [['proprietarioId'], 'exist', 'skipOnError' => true, 'targetClass' => Proprietario::className(), 'targetAttribute' => ['proprietarioId' => 'id']],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'numero' => 'Número',
            'condominioId' => 'Condomínio',
            'proprietarioId' => 'Proprietário',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getDebitos()
    {
        return $this->hasMany(Debito::className(), ['unidadeId' => 'id'])->inverseOf('unidade');
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getCondominio()
    {
        return $this->hasOne(Condominio::className(), ['id' => 'condominioId'])->inverseOf('unidades');
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getProprietario()
    {
        return $this->hasOne(Proprietario::className(), ['id' => 'proprietarioId'])->inverseOf('unidades');
    }

    public function getTotalDebitos()
    {
        return Debito::find()->andWhere(['unidadeId' => $this->id])->sum('totalDebito') ?: 0;
    }

    public function getHonorarios()
    {
        return round($this->getTotalDebitos() * 0.1, 2);
    }

    public function atualizarDebitos()
    {
        $debitos = $this->debitos;
        foreach ($debitos as $debito) {
            $debito->calcular();
        }
    }
}

frontend/controllers/CondominioController.php
<?php

namespace frontend\controllers;

use Yii;
use common\models\Condominio;
use common\models\search\CondominioSearch;
use yii\web\NotFoundHttpException;

/**
 * CondominioController implements the CRUD actions for Condominio model.
 */
class CondominioController extends MainController
{
    /**
     * Lists all Condominio models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new CondominioSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Condominio model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Condominio model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Condominio();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('create', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Updates an existing Condominio model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('update', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Deletes an existing Condominio model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Condominio model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Condominio the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Condominio::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}

frontend/controllers/ProprietarioController.php
<?php

namespace frontend\controllers;

use common\models\search\UnidadeSearch;
use Yii;
use common\models\Proprietario;
use common\models\search\ProprietarioSearch;
use frontend\controllers\MainController;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * ProprietarioController implements the CRUD actions for Proprietario model.
 */
class ProprietarioController extends MainController
{
    /**
     * Lists all Proprietario models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new ProprietarioSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Proprietario model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        $unidadeSearchModel = new UnidadeSearch(['proprietarioId' => $id]);
        $unidadeProvider = $unidadeSearchModel->search(Yii::$app->request->queryParams);

        return $this->render('view', [
            'model' => $this->findModel($id),
            'unidadeSearchModel' => $unidadeSearchModel,
            'unidadeProvider' => $unidadeProvider,
        ]);
    }

    /**
     * Creates a new Proprietario model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Proprietario();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('create', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Updates an existing Proprietario model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('update', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Deletes an existing Proprietario model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Proprietario model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Proprietario the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Proprietario::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}

frontend/controllers/UnidadeController.php
<?php

namespace frontend\controllers;

use common\components\Flash;
use common\models\Condominio;
use common\models\Debito;
use common\models\Proprietario;
use common\models\search\DebitoSearch;
use common\models\search\UnidadeSearch;
use common\models\Unidade;
use Yii;
use yii\base\InvalidParamException;
use yii\web\NotFoundHttpException;

/**
 * UnidadeController implements the CRUD actions for Unidade model.
 */
class UnidadeController extends MainController
{
    /**
     * Lists all Unidade models.
     * @return mixed
     */
    public function actionIndex()
    {
//        include_once '../../vendor/phpoffice/phpword/samples/Sample_09_Tables.php';

        $searchModel = new UnidadeSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Unidade model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        $debitosSearchModel = new DebitoSearch(['unidadeId' => $id]);
        $debitosProvider = $debitosSearchModel->search(Yii::$app->request->queryParams);

        return $this->render('view', [
            'model' => $this->findModel($id),
            'debitosSearchModel' => $debitosSearchModel,
            'debitosProvider' => $debitosProvider,
        ]);
    }

    /**
     * Displays a single Unidade model.
     * @param integer $id
     * @return mixed
     */
    public function actionAtualizarDebitos($id)
    {
        $unidade = $this->findModel($id);
        $unidade->atualizarDebitos();

        return $this->redirect(['view', 'id' => $id]);
    }

    /**
     * Displays a single Unidade model.
     * @param integer $id
     * @return mixed
     */
    public function actionMostrarTabela($id)
    {
        $unidade = $this->findModel($id);
        $this->render('tabelaScript', [
            'unidade' => $unidade,
            'debitos' => $unidade->debitos,
        ]);

        $file = '../views/unidade/tabelas/tabela.docx';
        if (file_exists($file)) {
            Yii::$app->response->sendFile($file);
        }

        return $this->render('tabela-erro');

    }

    /**
     * Creates a new Unidade model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Unidade();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            Flash::success('Unidade cadastrada com sucesso!');

            return $this->redirect(['index']);
        } else {
            return $this->render('create', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Creates a new Unidade model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionNovoCondominio()
    {
        $condominio = new Condominio();

        if ($condominio->load(Yii::$app->request->post()) && $condominio->save()) {
            Flash::success('Condomínio cadastrado com sucesso!');

            return $this->redirect(['index']);
        } else {
            Flash::error('Não foi possível cadastrar o condomínio');
            return $this->redirect('.');
        }
    }

    /**
     * Creates a new Unidade model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionNovoProprietario()
    {
        $proprietario = new Proprietario();

        if ($proprietario->load(Yii::$app->request->post()) && $proprietario->save()) {
            Flash::success('Proprietário cadastrado com sucesso!');

            return $this->redirect(['index']);
        } else {
            Flash::error('Não foi possível cadastrar o Proprietário');
            return $this->redirect('.');
        }
    }

    /**
     * @return mixed
     */
    public function actionNovoDebito()
    {
        $id = Yii::$app->request->get('id');
//        $id = ArrayHelper::getValue(Yii::$app->request->get('id'), 'id', false);

        if (!$id) {
            throw new InvalidParamException('Id da unidade não informado!');
        }

        $post = Yii::$app->request->post();
        $debito = new Debito(['unidadeId' => $id]);

        if ($post) {
            $debito->load($post);
            if ($debito->calcular()) {
                $this->redirect(['view', 'id' => $id]);
            }
        }

        return $this->render('_formDebito', [
            'debito' => $debito,
        ]);
    }

    /**
     * Updates an existing Unidade model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('update', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Deletes an existing Unidade model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * @param integer $id
     * @return mixed
     */
    public function actionLimparDebitos($id)
    {
        $unidade = $this->findModel($id);

        foreach ($unidade->debitos as $debito) {
            $debito->delete();
        }

        Flash::success('Débitos excluídos com sucesso!');
        return $this->redirect(['view', 'id' => $id]);
    }

    /**
     * Finds the Unidade model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Unidade the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Unidade::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}

frontend/views/unidade/_form.php
<?php

use common\models\Condominio;
use common\models\Proprietario;
use common\widgets\Select2;
use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model common\models\Unidade */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="unidade-form">

    <?php $form = ActiveForm::begin(); ?>

    <?= $form->field($model, 'numero')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'condominioId')->widget(Select2::className(), [
        'model' => $model,
        'initValueText' => Condominio::findOne($model->condominioId),
        'attribute' => 'condominioId',
        'objeto' => 'condominio',
    ]) ?>

    <?= $form->field($model, 'proprietarioId')->widget(Select2::className(), [
        'model' => $model,
        'initValueText' => Proprietario::findOne($model->proprietarioId),
        'attribute' => 'proprietarioId',
        'objeto' => 'proprietario',
    ]) ?>


    <div class="form-group">
        <?= Html::submitButton($model->isNewRecord ? 'Cadastrar' : 'Update', ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

frontend/views/unidade/_formDebito.php
<?php

use kartik\money\MaskMoney;
use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $debito common\models\Debito */
/* @var $form yii\widgets\ActiveForm */

?>

<div class="unidade-form">

    <?php $form = ActiveForm::begin(['action' => 'novo-debito?id=' . $debito->unidadeId]); ?>

    <?= $form->field($debito, 'descricao')->textInput(['maxlength' => true]) ?>

    <?= $form->field($debito, 'vencimento')->textInput(['type' => 'date']) ?>

    <?= $form->field($debito, 'valorOriginal')->widget(MaskMoney::className(), [
        'pluginOptions' => [
            'prefix' => 'R$',
            'allowNegative' => false,
            'thousands' => '.',
            'decimal' => ',',
            'precision' => 2,
        ],
    ]) ?>

    <div class="form-group">
        <?= Html::submitButton('Calcular', ['class' => 'btn btn-success']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

frontend/views/unidade/_menuUnidade.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model common\models\Unidade */


?>
<nav class="navbar navbar-default second-navbar">
    <div class="container-fluid">
        <div class="navbar-header">
            <span class="navbar-brand">
                <?= Html::a(Yii::t('app', 'Novo Débito'), ['novo-debito', 'id' => $model->id]) ?> ?>
            </span>
        </div>
        <div>
            <ul class="nav navbar-nav">
                <li><?= Html::a(Yii::t('app', 'Atualizar Débitos'), ['atualizar-debitos', 'id' => $model->id]) ?></li>
            </ul>
        </div>
    </div>
</nav>

frontend/views/unidade/_modalNovaUnidade.php
<?php
use common\models\Condominio;
use common\models\Proprietario;
use common\models\Unidade;
use common\widgets\Select2;
use kartik\helpers\Html;
use kartik\widgets\ActiveForm;
use yii\bootstrap\Modal;

Modal::begin([
    'header' => '<span id="nova-unidade-modal-title">Nova Unidade</span>',
    'id' => 'nova-unidade-modal',
    'size' => 'modal-lg',
    'clientOptions' => ['backdrop' => 'static', 'keyboard' => FALSE]
]); ?>
    <div id="nova-unidade-modal-content">
        <div class="unidade-form">

            <?php $unidade = new Unidade();
            $form = ActiveForm::begin(['action' => '/unidade/create']); ?>

            <?= $form->field($unidade, 'numero')->textInput(['maxlength' => true]) ?>

            <?= $form->field($unidade, 'condominioId')->widget(Select2::className(), [
                'model' => $unidade,
                'initValueText' => Condominio::findOne($unidade->condominioId),
                'attribute' => 'condominioId',
                'objeto' => 'condominio',
            ]) ?>

            <?= $form->field($unidade, 'proprietarioId')->widget(Select2::className(), [
                'model' => $unidade,
                'initValueText' => Proprietario::findOne($unidade->proprietarioId),
                'attribute' => 'proprietarioId',
                'objeto' => 'proprietario',
            ]) ?>

            <div class="form-group">
                <?= Html::submitButton('Cadastrar', ['class' => 'btn btn-success']) ?>
            </div>

            <?php ActiveForm::end(); ?>

        </div>
    </div>
<?php Modal::end(); ?>

frontend/views/unidade/_modalNovoCondominio.php
<?php
use common\models\Condominio;
use kartik\helpers\Html;
use kartik\widgets\ActiveForm;
use yii\bootstrap\Modal;

Modal::begin([
    'header' => '<span id="novo-condominio-modal-title">Novo Condomínio</span>',
    'headerOptions' => ['id' => 'modalHeader'],
    'id' => 'novo-condominio-modal',
    'size' => 'modal-lg',
    'clientOptions' => ['backdrop' => 'static', 'keyboard' => FALSE]
]); ?>
    <div id="novo-condominio-modal-content">
        <div class="condominio-form">

            <?php $condomino = new Condominio();
            $form = ActiveForm::begin(['action' => '/unidade/novo-condominio']); ?>

            <?= $form->field($condomino, 'razaoSocial')->textInput(['maxlength' => true]) ?>

            <?= $form->field($condomino, 'cnpj')->textInput(['maxlength' => true]) ?>

            <div class="form-group">
                <?= Html::submitButton('Cadastrar', ['class' => 'btn btn-success']) ?>
            </div>

            <?php ActiveForm::end(); ?>

        </div>
    </div>
<?php Modal::end(); ?>

frontend/views/unidade/_modalNovoProprietario.php
<?php
use common\models\Proprietario;
use kartik\helpers\Html;
use kartik\widgets\ActiveForm;
use yii\bootstrap\Modal;

Modal::begin([
    'header' => '<span id="novo-proprietario-modal-title">Novo Proprieário</span>',
    'headerOptions' => ['id' => 'modalHeader'],
    'id' => 'novo-proprietario-modal',
    'size' => 'modal-lg',
    'clientOptions' => ['backdrop' => 'static', 'keyboard' => FALSE]
]); ?>
    <div id="novo-proprietario-modal-content">
        <div class="proprietario-form">

            <?php $proprietario = new Proprietario();
            $form = ActiveForm::begin(['action' => '/unidade/novo-proprietario']); ?>

            <?= $form->field($proprietario, 'nome')->textInput(['maxlength' => true]) ?>

            <?= $form->field($proprietario, 'telefone')->textInput(['maxlength' => true]) ?>

            <?= $form->field($proprietario, 'email')->textInput(['maxlength' => true]) ?>

            <?= $form->field($proprietario, 'cpf')->textInput(['maxlength' => true]) ?>


            <div class="form-group">
                <?= Html::submitButton('Cadastrar', ['class' => 'btn btn-success']) ?>
            </div>

            <?php ActiveForm::end(); ?>

        </div>
    </div>
<?php Modal::end(); ?>

frontend/views/unidade/index.php
<?php

use common\models\Condominio;
use common\models\Proprietario;
use common\models\Unidade;
use common\widgets\Select2;
use kartik\helpers\Html;
use yii\grid\GridView;

/* @var $this yii\web\View */
/* @var $searchModel common\models\search\UnidadeSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Unidades';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="unidade-index">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= Html::button('Novo Condomínio', ['class' => 'btn btn-info',
        'data-toggle' => "modal", 'data-target' => "#novo-condominio-modal"
    ]) ?>

    <?= Html::button('Novo Proprietário', ['class' => 'btn btn-primary',
        'data-toggle' => "modal", 'data-target' => "#novo-proprietario-modal"
    ]) ?>

    <?= Html::button('Nova Unidade', ['class' => 'btn btn-success',
        'data-toggle' => "modal", 'data-target' => "#nova-unidade-modal"
    ]) ?>


    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'columns' => [
            [
                'attribute' => 'id',
                'headerOptions' => [
                    'class' => 'col-xs-3',
                ],
                'label' => 'Número',
                'value' => function ($model) {
                    return $model->numero .
                    Html::tag('sup', Html::a(Html::icon('new-window'), ['view', 'id' => $model->id], ['target' => '_blank']));
                },
                'contentOptions' => [
                    'class' => 'link-popup',
                ],
                'filter' => Select2::widget([
                    'model' => $searchModel,
                    'attribute' => 'id',
                    'initValueText' => Unidade::findOne($searchModel->id),
                    'objeto' => 'unidade',
                ]),
                'format' => 'raw',
            ],
            [
                'attribute' => 'condominioId',
                'headerOptions' => [
                    'class' => 'col-xs-4',
                ],
                'label' => 'Condomínio',
                'value' => function ($model) {
                    return $model->condominio .
                    Html::tag('sup', Html::a(Html::icon('new-window'), ['/condominio/view', 'id' => $model->condominioId], ['target' => '_blank']));
                },
                'contentOptions' => [
                    'class' => 'link-popup',
                ],
                'filter' => Select2::widget([
                    'model' => $searchModel,
                    'attribute' => 'condominioId',
                    'initValueText' => Condominio::findOne($searchModel->condominioId),
                    'objeto' => 'condominio',
                ]),
                'format' => 'raw',
            ],
            [
                'label' => 'Proprietário',
                'attribute' => 'proprietarioId',
                'headerOptions' => [
                    'class' => 'col-xs-5',
                ],
                'value' => function ($model) {
                    return $model->proprietario ? $model->proprietario .
                        Html::tag('sup', Html::a(Html::icon('new-window'), ['/proprietario/view', 'id' => $model->proprietarioId], ['target' => '_blank'])) : '';
                },
                'contentOptions' => [
                    'class' => 'link-popup',
                ],
                'filter' => Select2::widget([
                    'model' => $searchModel,
                    'attribute' => 'proprietarioId',
                    'initValueText' => Proprietario::findOne($searchModel->proprietarioId),
                    'objeto' => 'proprietario',
                ]),
                'format' => 'raw',
            ],

            [
                'class' => 'yii\grid\ActionColumn',
            ],
        ],
    ]); ?>
</div>
<?= $this->render('_modalNovoCondominio'); ?>
<?= $this->render('_modalNovaUnidade'); ?>
<?= $this->render('_modalNovoProprietario'); ?>

frontend/views/unidade/tabela.php
<?php

use kartik\helpers\Html;

/* @var $this yii\web\View */
/* @var $model common\models\Unidade */
/* @var $debitos common\models\Debito[] */
$formatter = Yii::$app->formatter;
$css = <<<CSS
.tabelaMostra{

    border: 1px;
 	width:auto; 
    margin-left:auto; 
    margin-right:auto;
	font: 10pt;
}

.tabelaMostra tr td {
    border: 1px solid #666;

}

.tabelaMostra th {
    border: 1px solid #666;
}
CSS;

$js = <<<JS
	var selectElementContents = function (el) {
    var body = document.body, range, sel;
    if (document.createRange && window.getSelection) {
        range = document.createRange();
        sel = window.getSelection();
        sel.removeAllRanges();
        try {
            range.selectNodeContents(el);
            sel.addRange(range);
        } catch (e) {
            range.selectNode(el);
            sel.addRange(range);
        }
    } else if (body.createTextRange) {
        range = body.createTextRange();
        range.moveToElementText(el);
        range.select();
    }
}
JS;


$this->registerCss($css);
$this->registerJs($js);


?>
<div class="tabela-debitos">
    <div class="row">
        <div class="col-xs-12">
            <?php /*
            <?= Html::button('<span class="glyphicon glyphicon-copy"></span> ' . 'Copiar Tabela', [
                'class' => 'btn btn-info',
                'onclick' => "selectElementContents($('.tabelaMostra') );",
            ])
            */ ?>

            <?= Html::a('Voltar', ['/unidade/view', 'id' => $model->id], [
                'class' => 'btn btn-default',
            ]) ?>
        </div>
        <hr>
        <div class="col-xs-12" id="tabela">
            <table class="tabelaMostra">

                <tbody>
                <tr>
                    <th>Descrição</th>
                    <th>Valor</th>
                    <th>Vencimento</th>
                    <th>Multa</th>
                    <th>Atualização</th>
                    <th>Valor Atualizado</th>

                    <th>Total de Juros</th>
                    <th>Total do Débito</th>
                </tr>

                <?php foreach ($debitos as $debito) : ?>
                    <tr>
                        <td><?= $debito->descricao ?></td>
                        <td><?= $formatter->asCurrency($debito->valorOriginal) ?></td>
                        <td><?= $formatter->asDate($debito->vencimento) ?></td>
                        <td><?= $formatter->asCurrency($debito->valorMulta) ?></td>
                        <td><?= str_replace('.', ',', $debito->atualizacao->fator) ?></td>
                        <td><?= $formatter->asCurrency($debito->valorAtualizado) ?></td>

                        <td><?= $debito->getMesesVencidos() . '% - ' . $formatter->asCurrency($debito->totalJuros) ?></td>
                        <td class="text-right"><?= $formatter->asCurrency($debito->totalDebito) ?></td>
                    </tr>
                <?php endforeach; ?>

                <tr>
                    <th>Soma dos Débitos:</th>
                    <th><?= $formatter->asCurrency($model->getTotalDebitos()) ?></th>
                </tr>
                <tr>
                    <th>Honorários:</th>
                    <th><?= $formatter->asCurrency($model->getHonorarios()) ?></th>
                </tr>
                <tr>
                    <th>Soma Total:</th>
                    <th><?= $formatter->asCurrency((float)($model->getHonorarios()) + (float)($model->getTotalDebitos())) ?></th>
                </tr>
                </tbody>
            </table>
        </div>
    </div>
</div>